---
abstract: 'convert a url into a html embed string'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: HTML::Video::Embed
name: HTML-Video-Embed
no_index:
  directory:
    - inc
    - t
requires:
  Data::Validate::URI: 0
  Module::Find: 0
  Moose: 0
  Moose::Role: 0
  URI: 0
  URI::Escape::XS: 0
  URI::QueryParam: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.007
